//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class PublicConstants
	{
		// Speed constants used in path finding to find the shortest path.
		// These represent the distance that each person travels in an update step.
		public static double SPEED_UNIMPROVED = 1.0;
		public static double SPEED_FOOTPATH   = 1.5;
		public static double SPEED_BIKE_TRAIL = 3;
		public static double SPEED_ROAD       = 10;
		public static double SPEED_BOULEVARD  = 15;
		public static double SPEED_RAIL       = 20;
	}
}

